### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by daumling** [RootRobotics/root-robot-ble-protocol#1]
I am currently intrgeating the protocol into Terrapin Logo. Questions:

- I am not sure how the color sensors work. Your app seems to use 5 areas, but how would these match to 32 color sensors. Also, how would I use the color light settings, if at all? Any info would be welcome.

- Saying does not seem to work. I tried a simple "HI", but no sound and no response.

Terrapin Logo is a Web app using Web Bluetooth with Chrome 70. I noticed that requesting a device descriptor returns a device with no name, and Chrome's selection dialog displays the bot as Unknown device (oddly enough, this happens on the first connect attempt after a page load; subsequent attempts display the device name just fine). See attached image.

Please also note that no implementation of Web Bluetooth supports listening to advertisements yet.

Regards, Michael

![root_pairing](https://user-images.githubusercontent.com/15716793/47806264-a079a080-dd39-11e8-9d72-922bfc7cb7ee.png)

**Comment by mogenson** [comment]
The robot has 32 independent color sensors and reports the detected color for each sensor as [32 4-bit nibbles packed into a 16 byte payload](https://github.com/RootRobotics/root-robot-ble-protocol#command-2---color-sensor-event). The Root Coding app combines sensors into 5 zones on the app level so that the user has to select fewer desired colors to trigger the When Color block. The following maps sensors to zones from left to right:
* zone 1: sensors 1 through 6
* zone 2: sensors 7 through 12
* zone 3: sensors 13 through 20
* zone 4: sensors 21 through 26
* zone 5: sensors 27 through 32

You don't have to do any configuration to start receiving color detection events. Just subscribe to the TX characteristic and parse the incoming packets. A new packet will be sent whenever one of the 32 sensors detects a new color, but no faster than 20 Hz.

Setting the color of the bottom color-sensing LEDs is for requesting a raw color sensor measurement instead of using the color detected event packets.

The say phrase command was added in main-board firmware version 1.3. You can check the version of your robot using the check firmware version packet or by letting the Root Coding app update your robot to the latest firmware version. This is the same command the first activity in the Learn section of the App uses to have the robot say its name.

Finally, the Generic Attribute Profile name was being cached by iOS so that the Root Coding app would not know when a robot was renamed. The robot includes its name as part of the advertising packet so changes can been seen in real time. Unfortunately, it sounds like Web Bluetooth doesn't support reading from advertising packets. Hopefully, this will change in the future.

**Comment by daumling** [comment]
Thank you - this is very helpful. A quick follow-up question: How does the app detect a color change in one of these blocks? When only one sensor reports the desired color, or when the majority of sensors report that change?

I am not a BT expert, but it may be helpful to supply the bot's name and device type during the detection sequence. People (in my case, young students) will be confused if they see an unknown device instead of a Root bot.

Is there an API to upgrade the firmware? Terrapin Logo is mostly used in schools, and I cannot see teachers using an iOS table to upgrade all of their bots. If Terrapin Logo could implement that functionality, it would be very helpful.

BTW - I tried to pair the bot with a Chromebook, and the system dialog would not even list the bot. Terrapin Logo on an Android tablet listed the bot just fine by name.

**Comment by mogenson** [comment]
Currently the When Color block triggers when at least one sensor inside the selected zone flips to the selected color. However, that's an app-specific decision. The 5 zones and trigger criteria are unrelated to the functionality of the robot's color sensor and the BLE protocol.

I'm not very knowledgeable about Web Bluetooth but I can comment some more on the robot's BLE implementation.

The advertising packet is 22 bytes long and contains the UART service UUID:
- Byte 0: Length = 2
- Byte 1: AD type = flags
- Byte 2: General Mode
- Byte 3: Length = 17
- Byte 4: 128-bit UUID following
- Bytes 5 to 20: UART service UUID

The scan response packet is 24 bytes long and contains the device name and dynamic service data:
- Byte 0: Length = 5
- Byte 1: AD type = Complete local name
- Bytes 2 to 17: Device name
- Byte 18: Length = 5
- Byte 19: AD type = Service data
- Bytes 20 to 21: 16-bit UUID
- Bytes 22 to 23: Service data

After connection the device name is available via a Root robot BLE protocol command or under the Generic Access service `(UUID: 0x1800)` and Device Name characteristic `(UUID: 0x2A00).`

So the robot's name is available in the scan response packet without connecting. Android, iOS, and Google Chrome via `chrome://bluetooth-internals/#devices` pick the name up and display it automatically. I'm unsure if this requires additional work using the Web Bluetooth API.

There is no public API to update the robot's firmware. The firmware updates are encrypted and signed so we'd like to keep them managed by our Root Coding app.

Let me know if this information helps. Many of us at Root Robotics had our first experience with coding using LOGO and were inspired by the LOGO turtle robots. I'm excited to see Root work with Terrapin LOGO!

**Comment by daumling** [comment]
Excellent! This is very helpful. I hope you don't mind that I file a Chromium bug with this information - the BLE Chooser is definitely buggy there.

**Comment by daumling** [comment]
How can I contact you per email? I'd like to offer you a Terrapin Logo license code.

**Comment by mogenson** [comment]
Feel free to share any information here.

Send a license to team@rootrobotics.com and I'd be happy to try it out!

**Comment by daumling** [comment]
Will do! I've filed a Chromium bug for Web Bluetooth FYI: https://bugs.chromium.org/p/chromium/issues/detail?id=904100
