### ISSUE TITLE
Root RT0 not responding to most motor commands

### ISSUE THREAD

**Issue by jwjordan** [RootRobotics/root-robot-ble-protocol#17]
I hope this is something simple that I'm missing, but I can only get my Root to respond to a few motor commands (drive distance and right motor speed). For clarity, here's what I'm sending to the Root for each different command I'm trying:

drive_distance: <Buffer 01 08 00 00 00 00 64 00 00 00 00 00 00 00 00 00 00 00 00 da>
right_speed: <Buffer 01 07 00 00 00 00 64 00 00 00 00 00 00 00 00 00 00 00 00 5b>
rotate_angle: <Buffer 01 12 00 00 00 17 70 00 00 00 00 00 00 00 00 00 00 00 00 99>
reset_position: <Buffer 01 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa>
drive_arc: <Buffer 01 27 00 00 00 1c 02 00 00 00 c8 00 00 00 00 00 00 00 00 41>

The first two work, and the other three don't. I don't get anything transmitted back from the Root on the failed commands either. I'm assuming maybe my checksum values are wrong, but I'm using the same crc library for generating all the checksums. Any ideas on what I might be doing wrong? FWIW, I have put the robot in ROOT BOOT mode and updated the firmware, just to be sure that wasn't the cause. And I can use the coding website and app to rotate the angle, so the Root definitely *works* from that perspective. Thanks for any assistance you can provide!

**Comment by shamlian** [comment]
Your buffers appear to be in hex but the command numbers in the protocol README are given in decimal. If that's right, your CRCs are correct given your buffer, but your commands are wrong, because you are mixing hex and decimal. Change `12` to `0c`, `15` to `0f`, and `17` to `11`, re-compute CRCs (your algorithm to do this seems correctly), and try again. (I suspect this is also true of your values you are passing by hand -- you probably mean `40` and not `64` in your payloads, for example.) Out of curiosity, what language are you using?

**Comment by jwjordan** [comment]
Fantastic! Thanks for the fast response, and this is 100% my problem. To answer your question, I am working with Javascript in an attempt to write a library for the Root RT0 for JS, but today I stumbled across this ([https://github.com/matths/root-robot-ble-javascript]) which actually works quite well, and further supports your point that I was mixing hex and decimal values. No need to reinvent the wheel, so I'll just utilize the existing library instead. Thank you again for the help though, it was a learning experience!
