### ISSUE TITLE
Command 4.1 - Color Sensor Data Response - is confusing

### ISSUE THREAD

**Issue by shamlian** [RootRobotics/root-robot-ble-protocol#7]
Description from #5 as follows;

> ## Command 4.1 - Color Sensor Data Response
> 
> With this command, I don't know how to handle the color data I receive, either with ADC or mV format. Is there a way to map the data with RGB colors or is it only brightness data?
> 
> Also the protocol says that the result for ADC format is on 12 bits but I get significant bits in the 16 bits of the color data.

**Comment by shamlian** [comment]
This command only returns brightness data for each bank of sensors given a particular lighting condition. A place to start could be to write a routine to convert to an RGB color based on the response on a particular bank illuminated in red, then green, and then blue, and then scaling appropriately. Some experimentation may be necessary to tune the output to your liking.

In millivolts mode, each 2-byte value should be in the range [0, 1000]; the ADC should report a 12-bit value. Note these are big-endian. Can you give me an example of a packet with incorrect data? I cannot reproduce this. (Also, please provide the versions of firmware on your main and color boards. I am testing with both boards at version 2.0,)

**Comment by entwanne** [comment]
Thanks for your answer!

Yes, my intention was to write such a function to get an RGB response, that's why I'm trying to understand the data I get.
But I'm sorry, I thought I always treated numbers as big-endian, but it seems that in this case I got them as little-endian, so there is no issue with 12-bit format.

For the record, my root versions are 2.0 for both boards (mainboard: firmware=2.0, hardware=1.1, bootloader=1.0, protocol=1.2; colorboard: firmware=2.0, hardware=1.0, bootloader=1.0, protocol=1.0).

But I still don't understand how I can map the values I receive to RGB. You say I should calibrate the robot with some colors I know to make suitable transformations?

I put the robot on a blue surface, and here are the requests I send to the robot and the responses I get:

### Get color data from left sensor (ADC) - all lightnings

<table>
  <tr>
    <th>Dev</th>
    <th>Cmd</th>
    <th>ID</th>
    <th colspan="16">Payload</th>
    <th>CRC</th>
  </tr>
  <tr>
    <td>4</td>
    <td>1</td>
    <td>Inc.</td>
    <td>Bank</td>
    <td>Lighting</td>
    <td>Format</td>
    <td colspan="13"></td>
    <td></td>
  </tr>
  <tr><td>4</td><td>1</td><td>4</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>153</td></tr>
</table>

<table>
  <tr>
    <th>Dev</th>
    <th>Cmd</th>
    <th>ID</th>
    <th colspan="16">Payload</th>
    <th>CRC</th>
  </tr>
  <tr>
    <td>4</td>
    <td>1</td>
    <td>Req.</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td></td>
  </tr>
  <tr><td>4</td><td>1</td><td>4</td><td>0</td><td>170</td><td>0</td><td>178</td><td>0</td><td>207</td><td>0</td><td>232</td><td>0</td><td>244</td><td>1</td><td>3</td><td>1</td><td>62</td><td>1</td><td>30</td><td>237</td></tr>
</table>

### Get color data from left sensor (ADC) - blue lightning

<table>
  <tr>
    <th>Dev</th>
    <th>Cmd</th>
    <th>ID</th>
    <th colspan="16">Payload</th>
    <th>CRC</th>
  </tr>
  <tr>
    <td>4</td>
    <td>1</td>
    <td>Inc.</td>
    <td>Bank</td>
    <td>Lighting</td>
    <td>Format</td>
    <td colspan="13"></td>
    <td></td>
  </tr>
  <tr><td>4</td><td>1</td><td>5</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>149</td></tr>
</table>

<table>
  <tr>
    <th>Dev</th>
    <th>Cmd</th>
    <th>ID</th>
    <th colspan="16">Payload</th>
    <th>CRC</th>
  </tr>
  <tr>
    <td>4</td>
    <td>1</td>
    <td>Req.</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td></td>
  </tr>
  <tr><td>4</td><td>1</td><td>5</td><td>0</td><td>110</td><td>0</td><td>111</td><td>0</td><td>129</td><td>0</td><td>141</td><td>0</td><td>134</td><td>0</td><td>139</td><td>0</td><td>185</td><td>0</td><td>169</td><td>97</td></tr>
</table>

### Get color data from left sensor (mV) - all lightnings

<table>
  <tr>
    <th>Dev</th>
    <th>Cmd</th>
    <th>ID</th>
    <th colspan="16">Payload</th>
    <th>CRC</th>
  </tr>
  <tr>
    <td>4</td>
    <td>1</td>
    <td>Inc.</td>
    <td>Bank</td>
    <td>Lighting</td>
    <td>Format</td>
    <td colspan="13"></td>
    <td></td>
  </tr>
  <tr><td>4</td><td>1</td><td>6</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>96</td></tr>
</table>

<table>
  <tr>
    <th>Dev</th>
    <th>Cmd</th>
    <th>ID</th>
    <th colspan="16">Payload</th>
    <th>CRC</th>
  </tr>
  <tr>
    <td>4</td>
    <td>1</td>
    <td>Req.</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td></td>
  </tr>
  <tr><td>4</td><td>1</td><td>6</td><td>0</td><td>41</td><td>0</td><td>43</td><td>0</td><td>50</td><td>0</td><td>56</td><td>0</td><td>59</td><td>0</td><td>63</td><td>0</td><td>77</td><td>0</td><td>69</td><td>88</td></tr>
</table>

### Get color data from left sensor (mV) - blue lightning

<table>
  <tr>
    <th>Dev</th>
    <th>Cmd</th>
    <th>ID</th>
    <th colspan="16">Payload</th>
    <th>CRC</th>
  </tr>
  <tr>
    <td>4</td>
    <td>1</td>
    <td>Inc.</td>
    <td>Bank</td>
    <td>Lighting</td>
    <td>Format</td>
    <td colspan="13"></td>
    <td></td>
  </tr>
  <tr><td>4</td><td>1</td><td>7</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>108</td></tr>
</table>

<table>
  <tr>
    <th>Dev</th>
    <th>Cmd</th>
    <th>ID</th>
    <th colspan="16">Payload</th>
    <th>CRC</th>
  </tr>
  <tr>
    <td>4</td>
    <td>1</td>
    <td>Req.</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td colspan="2">Data</td>
    <td></td>
  </tr>
  <tr><td>4</td><td>1</td><td>7</td><td>0</td><td>27</td><td>0</td><td>27</td><td>0</td><td>32</td><td>0</td><td>34</td><td>0</td><td>32</td><td>0</td><td>34</td><td>0</td><td>45</td><td>0</td><td>40</td><td>62</td></tr>
</table>

**Comment by shamlian** [comment]
Your color sensor data looks correct; this is the fidelity of data used to determine detected colors in the app. The Root color sensor is similar to a handheld wand scanner (search for "contact image sensors" to learn more about the idea), but at a much lower resolution, with much less regular lighting. One approach to get an RGB value could be to take data from the color sensor three times -- once with red, once with green, and once with blue illumination -- and then to scale them by some factor in order to get them to fit in a standard 24-bit RGB tuple (8 bits per channel). One scale factor could be, if using 12-bit data, to divide by 4096 (12 bits) and then multiply by 256 (8 bits) per channel (or, in one step, to just divide by 16), but I suspect you will find this color to be a bit dark. A better scale factor might be found by placing your robot's sensor on a piece of white copy paper or a whiteboard and using that to determine the maximum value for a particular channel. You may similarly want to calibrate on a black surface, as well.

**Comment by entwanne** [comment]
Ok thanks, I wasn't sure if I could get a direct answer by taking the color data with all lightnings.

So do you know how color events work? The robot continually switch the different LEDs while running to detect the colors?

**Comment by shamlian** [comment]
Yes, the robot switches which LEDs are on and samples the sensor repeatedly in order to detect color. You can see this switching if you flip the robot over while it's on and cover the cliff sensor (so that it thinks it is on the floor), and then move the robot around a little bit, sort-of like a persistence-of-vision display.

**Comment by entwanne** [comment]
Yes I already seen these LEDs lightning but I thought they were all turned on simulltaneously, not color by color.
Then do you know what is the purpose of the all-led-lightning parameter: it's to get a representation of the ambiant luminosity?

Thank you for your explanations, Then I'll try to make some calibration to get the RGB conversion.

**Comment by shamlian** [comment]
I do not know for sure as I am not the original designer, but I could speculate that if time was of the essence, one might use "all LEDs on" lighting if they were interested in keying on a feature regardless of its color. If the robot is moving while measurements are taken, it's not always looking at the same slice of the world; there might be an application where knowing something is below you is more important than knowing exactly what color it is. Closing this issue for now; you're welcome to open a new issue if you have this or any other problems (unfortunately because of how Github issues are designed, I do not believe you will be able to re-open this one).
